### ISSUE TITLE
Support rewriting ValueTask

### ISSUE THREAD

**Issue by campler** [microsoft/coyote#188]
ValueTasks are an important TPL type and although one can replace their usage with Task in their own code, many common 3rd party and system libraries use them. Most notably is the Microsoft.AspNetCore.Mvc.Testing library depends on HttpClient which uses ValueTask. Another example is Autofac's DisposeAsync.

This is a known limitation, just wanted to create an issue to put it on the roadmap.

**Comment by pdeligia** [comment]
Thanks for adding this issue @campler, I agree this is an important TPL type and has been in our minds. We do not currently have an ETA for this, but we do want to add support for it in the rewriter.
