### ISSUE TITLE
Tools used in coyote

### ISSUE THREAD

**Issue by jtourvieille** [microsoft/coyote#20]
Hello
I like your product, congrat!
I have a question: which tool did you use to build the animated state machine demo? https://microsoft.github.io/coyote/learn/programming-models/actors/state-machine-demo

**Comment by lovettchris** [comment]
I answered on Gitter, so I'll copy the same answer here :-) I'm glad to hear you like Coyote. The animations are easy to create, first you use our "coyote" tool to run a test with `--graph-bug` and `--xml-trace`. The `--xml-trace` file is used to play back the animation. The `--graph-bug` option produces a DGML diagram which you can load into Visual Studio 2019 (assuming you've enabled the DGML Editor optional component in the VS installer). Then you will need the [DGMLPowerTools ](https://marketplace.visualstudio.com/items?itemName=ChrisLovett.DgmlPowerTools2019) extension for VS 2019, this adds a "Save as SVG" option on the DGML Share toolbar. But first you will need to change the "Link" layout using the Layout menu on the toolbar to "show all cross group links". Then save the file. It's prettier if you also enable edge bundling layout option. Then to run this in a web page you need the 3 javascript modules `progress_bar.js`, `animate_trace.js` and `trace_model.js`, and a <div> element that ties it all together like this: 
```html
<div class="animated_svg" trace="/coyote/assets/data/Raft.xml" svg="/coyote/assets/images/Raft.svg" ></div>
```
The progress bar is also a bunch of UI controls that the progress_bar.js expects to find, which you can find in [player-controls.html](https://github.com/microsoft/coyote/blob/master/docs/_includes/player-controls.html).

**Comment by pdeligia** [comment]
Closing this for now as it was answered.
