### ISSUE TITLE
Can't build coyote from x64 command prompt

### ISSUE THREAD

**Issue by lovettchris** [microsoft/coyote#227]
call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"

Would be nice if we can fix that because I need to use x64 for all my c++ projects, so would be nice if coyote also was friendly to this environment...

![image](https://user-images.githubusercontent.com/18707114/136634822-1f88b750-aa49-4852-91c8-719e1c0f9b60.png)

**Comment by pdeligia** [comment]
I was able to fix this by adding `/p:Platform=""Any CPU""` in the build script as seen below:
```powershell
if ($version_net4) {
        # Build .NET Framework 4.x as well as the new version.
        $command = $command + " /p:BUILD_NET462=yes /p:Platform=""Any CPU"""
    }

    if ($null -ne $version_netcore31 -and $version_netcore31 -ne $sdk_version) {
        # Build .NET Core 3.1 as well as the new version.
        $command = $command + " /p:BUILD_NETCORE31=yes /p:Platform=""Any CPU"""
    }
```

But I am not sure if its safe to just add it in the build script (safe from the perspective of the nuget packages that we publish), the solution already is defined with Any CPU, so its a bit strange that building from the script does not pick that up in the x64 command line ...
