### ISSUE TITLE
-- coverage support on dotnet core

### ISSUE THREAD

**Issue by ankushdesai** [microsoft/coyote#26]
Previous versions used to support `--coverage activity` on dotnet core.

Can we please re-enable it?

**Comment by lovettchris** [comment]
Fix is on it's way, the fix is very simple, jsut remove `|| configuration.ReportActivityCoverage` on line 380 of CommandLineOptions.cs.

**Comment by ankushdesai** [comment]
Thanks @lovettchris!

**Comment by pdeligia** [comment]
@ankushdesai the new 1.0.5 has this fix :) Closing this for now, but let us know if it still does not work for you!

**Comment by ankushdesai** [comment]
Thanks!
