### ISSUE TITLE
dotnet tool 6.0 support.

### ISSUE THREAD

**Issue by blacksmith01** [microsoft/coyote#264]
It's okay if I build and run coyote using the latest github source code.
but when I try run coyote in dotnet tool, I get the error like bellow.

![coyote 2022-01-05 195512](https://user-images.githubusercontent.com/567946/148210243-8cf18b22-6130-4c75-8f71-4223a53ed9bf.png)

**Comment by pdeligia** [comment]
@blacksmith01 thanks for reporting this issue, this should not be happening, I will investigate this and try see what is going on.

**Comment by pdeligia** [comment]
Btw, I see that in the 2nd line it says that this uses .NET Core 5, but it is trying to pick up `System.Runtime` v6, I think this causes the issue. I just quickly tried it locally, and if I build my application as .NET 5 the `coyote` tool loads it fine. We do not support .NET 6 yet on NuGet, but it will be supported on the next release (that is why from the main branch it worked).

**Comment by pdeligia** [comment]
This is now supported in Coyote [v1.4.2](https://www.nuget.org/packages/Microsoft.Coyote/1.4.2).
