### ISSUE TITLE
Unable to test optimistic concurrency for SQLite and EF core with Coyote

### ISSUE THREAD

**Issue by chintanr97** [microsoft/coyote#297]
We are having a API service that supports CRUD operations over some resource entities. Let us consider, one such entity like a `participant`. The API service in production hits the Azure SQL server deployment. The EF core corresponding to the entity can be identified as:
```csharp
modelBuilder.Entity<Participant>(entity =>
{
    entity.HasKey(e => e.Id)
        .IsClustered();

    entity.Property(e => e.Description)
        .IsRequired()
        .HasMaxLength(255);

    entity.Property(e => e.Name)
        .IsRequired()
        .HasMaxLength(255);

    entity.Property(e => e.RowVersion)
        .IsRequired()
        .IsRowVersion()
        .IsConcurrencyToken();
});
```

As one can note, we are using `rowversion` data type of SQL server to detect concurrency conflict using optimistic concurrency approach during parallel update/delete operation on the entity. 

Followed by this, we are writing a concurrency test suite with the help of `XUnit` and `Coyote` to test for the same using 2 concurrent update operations attempting to update a participant record. The test suite is run using the in-memory `SQLite` deployment. We have taken care that the SQLite is appropriately simulated with the rowversion behavior by configuring the default for that column as `randomblob(8)` and adding an `after-update` trigger to update the rowversion column value.

The following snippet is from the setup of executing the concurrency test method:
```csharp
var schedulerAssignments = new Func<Configuration, Configuration>[]
{
    (configuration) => configuration.WithRandomStrategy(),
    (configuration) => configuration.WithPCTStrategy(isFair: true),
};

foreach (var assignScheduler in schedulerAssignments)
{
    configuration = Configuration.Create()
        .WithTelemetryEnabled(false)
        .WithTestingTimeout(10)
        .WithTestingIterations(1000);
    RunTestForConfiguration(testAction, assignScheduler(configuration));
}

...

// RunTestForConfiguration
TestingEngine engine = TestingEngine.Create(configuration, testAction);
engine.Run();

var report = engine.TestReport;
if (report.NumOfFoundBugs != 0)
{
    var errorMessage = new StringBuilder()
        .AppendLine($"{report.NumOfFoundBugs} bug(s) found with scheduling strategy {configuration.SchedulingStrategy}.")
        .AppendLine($"Is test rewritten: {engine.IsTestRewritten()}")
        .AppendLine($"Bugs:")
        .AppendLine(string.Join('\n', report.BugReports))
        .AppendLine($"Logs:\n{engine.ReadableTrace}")
        .AppendLine($"Trace:\n{engine.ReproducibleTrace}");

    var traceFile = WriteReproducibleTrace(engine.ReproducibleTrace, "updatecall");

    throw new Exception(errorMessage.ToString());
}
```

The following is the snippet of the `testAction` being executed by Coyote:
```csharp
// Gets an existing participant
...

// Prepare update request payloads
var updateRequestPayload1 = new ParticipantUpdateRequest
{
    Description = "test1",
};
var updateRequestPayload2 = new ParticipantUpdateRequest
{
    Description = "test2",
};

// Send the parallel calls
var participantUpdateResponse1 = this.UpdateParticipantAsync(participant.Id, updateRequestPayload1);
var participantUpdateResponse2 = this.UpdateParticipantAsync(participant.Id, updateRequestPayload2);

// Wait for both tasks to complete
await Task.WhenAll(participantUpdateResponse1, participantUpdateResponse2);

// Assert that exactly any one of the operations succeeded
var updateResponse1 = participantUpdateResponse1.Result;
var updateResponse2 = participantUpdateResponse2.Result;

Assert.True(updateResponse1.IsSuccessful ^ updateResponse2.IsSuccessful);
```

The API hits the database as following snippet:
```csharp
var participantEntity = await this.context.Participants
    .FirstOrDefaultAsync(participant => participant.Id == participantId, cancellationToken);

participantEntity.Description = request.Description;

try
{
    await this.context.SaveChangesAsync(cancellationToken);
}
catch (Exception e)
{
    throw <someCustomizedException>;
}
```

Now, when I execute the test method using VS2019 and Test Explorer, I receive following error response:
```
System.Exception : 1 bug(s) found with scheduling strategy random.
Is test rewritten: True
Bugs:
Unhandled exception. Xunit.Sdk.TrueException: Assert.True() Failure
Expected: True
Actual:   False
The stack trace is:
...
Logs:
<TestLog> Running test.
<ErrorLog> Unhandled exception. Xunit.Sdk.TrueException: Assert.True() Failure
Expected: True
Actual:   False
The stack trace is:
...
<TestLog> Exploration finished [found a bug using the 'random' strategy].
<StrategyLog> Testing statistics:
<StrategyLog> Found 1 bug.
<StrategyLog> Scheduling statistics:
<StrategyLog> Explored 1 schedule: 1 fair and 0 unfair.
<StrategyLog> Found 100.00% buggy schedules.
<StrategyLog> Number of scheduling points in fair terminating schedules: 1 (min), 1 (avg), 1 (max).
Trace:
--liveness-temperature-threshold:50000
--fair-scheduling
(0)
```

As I had saved the reproducible trace in the schedule file, I replayed it by calling the `testAction` as:
```csharp
trace = File.ReadAllText(traceFile);

var config = Configuration.Create()
    .WithTelemetryEnabled(false)
    .WithReplayStrategy(trace);

TestingEngine engine = TestingEngine.Create(config, testAction);
engine.Run();
engine.ThrowIfBugFound();
```

and I observed that the both the request calls were made serially (i.e., the update request with description "test1" was saved and then the request began for update operation with description as "test2"). And in such a scenario it would be expected that both the calls succeed. So, I am not sure where I am going wrong for testing the optimistic concurrency with SQLite, EF core and Coyote. Please let me know if I am missing something here.

**NOTE**: If I simulate parallel calls just using `XUnit` and the in-memory SQLite instance, then I receive the `DbUpdateConcurrentException` as expected.

A possible summary of the query is: "We want Coyote to deterministically test for the scenario where the first request read the data, the second request succeeds completely, and first request then attempts to save the changes and fails with `DbUpdateConcurrentException`".

**Comment by pdeligia** [comment]
@chintanr97 and me are talking offline to resolve this issue.

**Comment by pdeligia** [comment]
Closing this issue as @chintanr97 and me resolved this offline.
