### ISSUE TITLE
migrate to Google Analytics 4

### ISSUE THREAD

**Issue by lovettchris** [microsoft/coyote#316]
[Google is turning off UA in July next year](https://blog.google/products/marketingplatform/analytics/prepare-for-future-with-google-analytics-4/)

So I've done some experiments with my XML Notepad and got everything to run on GA4.  The website change is trivial, see [XML notepad commit](https://github.com/microsoft/XmlNotepad/commit/f3659d51fcbc8ffed024dbcaa4802a70c6c59713)

I'd be happy to do this for Coyote if you like.  The downside is there's no easy history migration plan, so the recommended approach is to run both side by side for  a year, so we have as much new data as we need (1 year's worth) in the new system before Google turns off UA support.

**Comment by pdeligia** [comment]
Done in #317.
