### ISSUE TITLE
When i run the UnitTest example it passes where it should fail 

### ISSUE THREAD

**Issue by tbertenshaw** [microsoft/coyote#38]
The first example in the documentation here https://microsoft.github.io/coyote/learn/tools/unit-testing
passes. It doesn't seem to be picking up the `Specification.Assert(False)` as an fail?

```xml  
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Coyote" Version="1.0.12" />
    <PackageReference Include="Microsoft.Coyote.Test" Version="1.0.12" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.console" Version="2.4.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
```

```csharp
using Microsoft.Coyote.Specifications;
using Microsoft.Coyote.Tasks;
using Microsoft.Coyote.Runtime;
using Microsoft.Coyote;

using Microsoft.Coyote.SystematicTesting;
using Xunit;
using Xunit.Abstractions;

namespace TimboCoyote
{
    public class FirstTest
    {
        ITestOutputHelper Output;

        public Test(ITestOutputHelper output)
        {
            this.Output = output;
        }


        [Fact(Timeout = 5000)]
        public void RunCoyoteTest()
        {
            var config = Configuration.Create();
            TestingEngine engine = TestingEngine.Create(config, CoyoteTestMethod);
            engine.Run();
            var report = engine.TestReport;
            Output.WriteLine("Coyote found {0} bug.", report.NumOfFoundBugs);
        }

        private async Task CoyoteTestMethod()
        {
            // This is running as a Coyote test.
            await Task.Delay(10);
            Specification.Assert(false, "This test failed!");
        }
    }
}
```

did i use the incorrect `using` statements?

**Comment by akashlal** [comment]
@tbertenshaw End you test `RunCoyoteTest` with the following to tell `xunit` what you're testing for:
```
Assert.True(report.NumOfFoundBugs == 0);
```

Then you will see the test fail.

**Comment by pdeligia** [comment]
That's right, @tbertenshaw the `Specification.Assert` is currently only recognized by the `TestingEngine` of Coyote (or by the `coyote test` tool, if you run it from command line), and not from xUnit (or other unit testing frameworks). When `Specification.Assert` fails, its going to trigger a failure in the testing engine, but then you need to assert it as Akash said above to fail your unit test.

**Comment by tbertenshaw** [comment]
yeah i get that (or i did after scratching my head for a bit). Would make sense to add that line below the console. So its obvious, as it wasn't when i was trying to work out what i was missing.

**Comment by pdeligia** [comment]
Totally, great suggestion! And thanks for the PR, I will merge later today.

**Comment by tbertenshaw** [comment]
Glad I could help. Does anyone monitor the samples repo? I did a similar quick clarification pr there. Hope its ok https://github.com/microsoft/coyote-samples/pull/10

**Comment by pdeligia** [comment]
Awesome, that looks like a great fix too, thanks! Yes, we are monitoring that repo (and we try updating it frequently, e.g. .whenever we push a new nuget package out, or if we come up with a new sample).

**Comment by pdeligia** [comment]
Closing this one as its resolved.
