### ISSUE TITLE
Issue with Task.WhenAll(IEnumerable<Task> tasks) model.

### ISSUE THREAD

**Issue by arunt1204** [microsoft/coyote#41]
Using System.Tasks the **CallOnStart()** function (in below example) is called 3 times, where as using Coyote.Tasks it's being called 9 times.

**Example:**

        private class Observer
        {
            public string Name;
            public int Stage;

            public Observer(int stage, string str)
            {
                this.Stage = stage;
                this.Name = str;
            }
        }

        internal static int Count = 0;

        [Fact(Timeout = 5000)]
        public void TestWhenAll()
        {
            this.Test(async () =>
            {
            List<Observer> list = new List<Observer>();
            for (int i = 0; i < 3; i++)
            {
                list.Add(new Observer(1, "Task"));
            }

            foreach (IGrouping<int, Observer> group1 in list
                .GroupBy(oo => oo.Stage)
                .OrderBy(group => group.Key))
            {
                    await Task.WhenAll(group1.Select(oo => CallOnStart()));
            }
                Specification.Assert(Count == 3, "Value is '{0}' instead of 3.", Count);

                await Task.Delay(1);
            },
            configuration: GetConfiguration().WithTestingIterations(100));
        }

        internal static Task CallOnStart()
        {
            Count = Count + 1;
            return Task.CompletedTask;
        }

**Comment by pdeligia** [comment]
Thanks @arunt1204 for the report! We will look into this.

**Comment by pdeligia** [comment]
Fixed in 5e267914f352c57a87534fd99f5d68ae2d813fee.
