### ISSUE TITLE
Make OnEntryAttribute un-sealed

### ISSUE THREAD

**Issue by muwaqar** [microsoft/coyote#44]
I was wondering why is the [OnEntryAttribute](https://github.com/microsoft/coyote/blob/50aa6ea2e7c1c3da2081721f112b746ea2d489b1/Source/Core/Actors/StateMachine.cs#L1573) sealed?

I see InitializeState() function looks for OnEntryAttribute (or its derived classes, as signified by "true" argument in the [source](https://github.com/microsoft/coyote/blob/50aa6ea2e7c1c3da2081721f112b746ea2d489b1/Source/Core/Actors/StateMachine.cs#L1235)) to locate the entry action, which to me indicates there was some initial thought on making it un-sealed.

This is very useful in scenarios where we want to write abstractions around the Coyote StateMachine class - for example, I am trying to write one where I allow maintaining state of the machine in a persistent store, and overriding OnEntryArribute not only makes my job easier (as I can define my custom OnEntry function which handles checkpointing of state) but also hides the nitty gitty implementation complexity of how my abstraction is implemented from the user.

Alternative ways to accomplish this are possible but the above approach seems most seamless to end users for me, so was wondering if it is possible to enable this.

**Comment by akashlal** [comment]
Hi @muwaqar. I'm not sure if I follow your query. Do you want to define your own `OnEntry` attribute? That is, you want to do something like `class MyOnEntryAttribute : OnEntryAttribute` and then use `MyOnEntry` in your state machine class? If so, I don't really see how that will help. 

The following source line that you're referring to:
```
if (this.GetType().GetCustomAttribute(typeof(OnEntryAttribute), true) is OnEntryAttribute entryAttribute)
```
Will look up exactly the `OnEntryAttribute` on the `State` or any of its parent types. That is, the `true` applies to parent types of `this` rather than `OnEntryAttribute`. We do this because we do support inheriting of states. You can see examples [here](https://github.com/microsoft/coyote/blob/master/Tests/SystematicTesting.Tests/Actors/StateMachines/StateInheritanceTests.cs). Perhaps you can support your scenario by inheriting the state, not the attribute?

**Comment by muwaqar** [comment]
My apologies on the wrong reading of the code. The boolean parameter does apply to the source `element` and not the `attributeType` as I thought ([source](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.customattributeextensions.getcustomattribute?view=netcore-3.1#System_Reflection_CustomAttributeExtensions_GetCustomAttribute_System_Reflection_MemberInfo_System_Type_System_Boolean_)).

Essentially I am looking for a way to render a fixed OnEntry behavior for every state seamlessly for the user.

For example, the behavior I want to render is:

```
public Task OnStateEntry()
{
  this.DoSomePreAction();
  try
  {
    this.RenderStateBehavior();
  }
  finally
  {
    this.DoSomePostAction();
  }
}
``` 

where `this.DoSomePreAction()` and `this.DoSomePostAction()` are fixed (for state management or other stuff), and the user only needs to specify the actual state behavior `this.RenderStateBehavior()`.

I thought I would accomplish this by definiting a custom OnEntry attribute which takes the actual state behavior as an input and always runs the fixed `OnStateEntry()` for every state. But looks like this is not possible.

Any other suggestions on how to accomplish what I want without actually modifying every state behavior code to run a common delegate?

**Comment by akashlal** [comment]
How about the following.
```
class MyOnEntryAttribute : Attribute { }

abstract class MyStateMachine : StateMachine
{
   [OnEntry(nameof(OnStateEntry))]
   class BaseState : State { }

   public Task OnStateEntry()
   {
     this.DoSomePreAction();
     try
     {
        // look up this.CurrentState.GetType().GetCustomAttribute(typeof(MyOnEntryAttribute),true)
        // to find the method and invoke it here
     }
     finally
     {
       this.DoSomePostAction();
     }
   }
}
```

Then every state machine in your code should be of the form:
```
class FooStateMachine : MyStateMachine 
{
   [MyOnEntry(nameof(Bar))]
   class S1 : BaseState { }

   protected Task Bar() { ... }
}
```

Does this make sense? You will have to follow the convention that all states of your state machine inherit from `BaseState` and not from `State` directly. Perhaps you can add an assert in `OnStateEntry` to check for this.

**Comment by muwaqar** [comment]
Right, this makes sense, and similar to what I was trying to do before - just uses state inheritance instead of event inheritance to accomplish this. Will have to do some caching of delegates for states to avoid performance penalties, as the Coyote actors currently do ... but at least this unblocks the main scenario. Thanks a lot.

**Comment by lovettchris** [comment]
Nice solution Akash, and Muhammad, state persistence of actors is very interesting.  Love to see a demo when you get it working :-)
