### ISSUE TITLE
Isssue with Task.WhenAny/Task.WhenAll

### ISSUE THREAD

**Issue by arunt1204** [microsoft/coyote#45]
**Assertion error:** "Cannot wait for zero tasks to complete."
The below example throws assertion error when ran using coyote tasks. But, using System tasks it executes.

Using system task **Task.WhenAll(tasks);** with tasks.count == 0, the program executes successfully. The tasks.count not mandatory be greater than 0.

**Example:**

        [Fact(Timeout = 5000)]
        public void Test1()
        {
            this.Test(async () =>
            {
                Random r = new Random();
                var tasks = new List<Task>();
                if (r.Next(2) == 1)
                {
                    tasks.Add(Task.Delay(100));
                }
                await Task.WhenAll(tasks);
            },
            configuration: GetConfiguration().WithTestingIterations(1));
        }

**Comment by pdeligia** [comment]
Thanks @arunt1204, I believe this was already fixed a few commit ago, can you please confirm?

**Comment by arunt1204** [comment]
Sorry @pdeligia, now I did the pull from latest commit and tested. Below are my findings,

Task.WhenAll(tasks) works fine, but Task.WhenAny doesn't.
It throws **System.ArgumentException**. Using system task it doesn't throws the exception.

Please confirm.

**Comment by pdeligia** [comment]
The `Task.WhenAny` is working as expected, I think this is a different bug related to the internal unit testing infrastructure of coyote, so closing this issue.
