### ISSUE TITLE
Standalone Actors

### ISSUE THREAD

**Issue by samcov** [microsoft/coyote#46]
Is it possible to use the Actors alone, without the rest of the framework?

Are the Actors extracted from another Microsoft project, and if so which one.

**Comment by akashlal** [comment]
Yes, absolutely. The [Microsoft.Coyote](https://www.nuget.org/packages/Microsoft.Coyote/) package is all you need. It contains the entire Actor implementation. There are no dependencies on other Microsoft projects.

**Comment by samcov** [comment]
The Actors in Coyote have dependencies on other parts of Coyote, but they don't seem to be big dependencies.
using Microsoft.Coyote.IO;
using Microsoft.Coyote.Runtime;

**Thanks, I'll give this a try.**
