### ISSUE TITLE
Unreachable side menu on https://microsoft.github.io/coyote/

### ISSUE THREAD

**Issue by gabthau** [microsoft/coyote#52]
On both Firefox and Edge, the left side menu is misplaced, sometimes to the point of either not appearing on the screen at all or being mostly unusable. Depending on the screen resolution and the content of the side menu, the menu position moves up and down.

This issue makes part of the documentation undiscoverable/unreachable for visitors if like me there are unlucky enough to hit the wrong browser/resolution combination.

Please see the screenshots below.

![Install page in Firefox](https://user-images.githubusercontent.com/24879810/93891122-5ada6e00-fceb-11ea-884a-39f7b627b49f.png)

![Learn page in Firefox](https://user-images.githubusercontent.com/24879810/93891269-8a897600-fceb-11ea-851a-943262c0cb8e.png)

![Case study page in Firefox-ff](https://user-images.githubusercontent.com/24879810/93891334-99702880-fceb-11ea-943e-39b19feec1a1.png)

![Learn page in Edge: the search box cannot be reached](https://user-images.githubusercontent.com/24879810/93891504-c58ba980-fceb-11ea-9694-6d8fba53a3b8.png)

As a side note: on the last screenshot, notice the UI dark pattern to nudge users to accept all cookies, in particular the lack of a "Decline all" button to complement the "Accept all" button. It gets even worse if you click the "Manage cookies" button. This kind of pattern is understandable (although ethically questionable) on website depending on third-party tracking to monetize, but it is rather puzzling to see that on a Microsoft funded software project documentation page. I'd be grateful if you provide this feedback to whomever can influence that decision.

**Comment by lovettchris** [comment]
Thanks for the bug reports.  The content of the cookie banner is centralized across all of Microsoft and worked out to comply with EU regulations as best as possible, so it's not something the Coyote team controls.  There are "Reject" buttons on all the options under "Manage Cookies".  We of course do not use advertising on this site, but it is a template that all Microsoft sites have to follow.

**Comment by lovettchris** [comment]
the firefox bug is fixed.  the crowding of logo by cookie banner is not, but it is lower priority.

**Comment by gabthau** [comment]
It's much better now, thanks. And thanks for all the work put in the documentation.

**Comment by lovettchris** [comment]
Great, glad to hear it, thanks for closing the loop.
